services:
  - type: web
    name: packaroji
    runtime: python
    buildCommand: pip install -r Packaroji/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --chdir Packaroji app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.11"
